### ISSUE TITLE
Temporal CLI based ephemeral server

### ISSUE THREAD

**Issue by bergundy** [temporalio/sdk-ruby#117]

**Comment by bergundy** [comment]
Depends on https://github.com/temporalio/sdk-core/issues/485

No need to maintain support for Temporalite.

**Comment by josh-berry** [comment]
How is this different from `temporal server start-dev`?

**Comment by cretz** [comment]
Our SDKs offer a programmatic interface to that that also downloads it and such

**Comment by lorensr** [comment]
https://typescript.temporal.io/api/classes/testing.TestWorkflowEnvironment#createlocal

**Comment by cretz** [comment]
The SDK is undergoing a rewrite/refresh and this issue applied to a previous version and is no longer applicable
