### ISSUE TITLE
Issue with using Temporal ruby-sdk

### ISSUE THREAD

**Issue by RondaPriyatham** [temporalio/sdk-ruby#130]
Description:
Trying to use Temporal services using ruby sdk. I have tried to implement the temporal services for java tool and it worked well. so I want to use the same services to the ruby tool. When I tried to implement it, produces the following error.
![image](https://user-images.githubusercontent.com/91109272/224953995-066332d5-5de0-4dd6-b956-6925f3558043.png)

Note: I have not used 'temporal' word anywhere. I have used Temporalio in particular.

System setup:
Using ruby 3.0.4
rustc version: 1.68.0
and installed other gems required for temporalio as described in documentation.
Have pulled the docker image and running the temporal on localhost.

-Output for "gem list" command. (please find that there is temporalio gem installed already).
![image](https://user-images.githubusercontent.com/91109272/224955441-cdd4e785-e2f0-4a2d-9c7e-6d9a83d4a7e4.png)

-bundle install command output for the directory which contains all the project files with Gemfile.
![image](https://user-images.githubusercontent.com/91109272/224955266-e426d65f-7c27-4793-bf9a-0db45bcfb18c.png)

I have referred to the issue in which it has described the name change of sdk from temporal to temporalio. But few snippets in the documentation still refer it as temporal. Please do check for that too.
And please let me know what can I do for this issue.

**Comment by mjameswh** [comment]
I think this should work correctly in version 0.1.1.

Could you please try that again? I'll close this issue in the mean time, but please reopen it if you still get the same behaviour.
