### ISSUE TITLE
[Bug] Release assets bear incorrect version number

### ISSUE THREAD

**Issue by mjameswh** [temporalio/sdk-ruby#132]
### Describe the bug
On GitHub's release page ([example](https://github.com/temporalio/sdk-ruby/releases/tag/v0.1.0-alpha)), assets are systematically named `bridge-0.0.1-ruby...`. The version number should be updated to reflect actual release number.

### Additional context
This version number comes from Bridge's Cargo.toml file. We need to update the version number in that file in the pre-release commit.

**Comment by cretz** [comment]
The SDK is undergoing a rewrite/refresh and this issue applied to a previous version and is no longer applicable
