### ISSUE TITLE
Find a way to mark unstable/private API

### ISSUE THREAD

**Issue by antstorm** [temporalio/sdk-ruby#79]

**Comment by laertispappas** [comment]
The most common thing I've seen here is via comments / documentation. If we want to force 
"java" like visibility here maybe a combination of `private_constant` and `private/protected` scope can solve the issue. Although this will goes a bit away from Ruby idioms though.

Example:

```
# public scope
module. Temporal
  class Worker
    def initialize(...)
       @activity_worker = create_activity_worker(core_worker, data_converter, activity_executor)
    end
  end  
  
  
  # Private scope
  class Worker
     class Activity; end
     private_constant Activity
    
     private

     def create_worker(...)
        Activity.new(...)
     end
  end
  
```

**Comment by antstorm** [comment]
I think this one should work well for us — https://rubydoc.info/gems/yard/file/docs/Tags.md#private
