### ISSUE TITLE
[Feature Request] Document a comparison with Coinbase Temporal Ruby library

### ISSUE THREAD

**Issue by haimgel** [temporalio/sdk-ruby#91]
I think it would be great to include in the README a comparison with the [Temporal Ruby library](https://github.com/coinbase/temporal-ruby) started by Coinbase, e.g. motivation behind starting this project rather than contribute to an already existing one, how this one would differ, why would I want to use one over the other, etc.

**Comment by cretz** [comment]
The SDK is undergoing a rewrite/refresh and this issue applied to a previous version and is no longer applicable
